sudo: false # http://docs.travis-ci.com/user/workers/container-based-infrastructure/
language: node_js
node_js:
  - 4
  - 6
  - 8

notifications:
  email:
    - medikoo+fs2@medikoo.com

script: "npm test && npm run lint"
